<?php

namespace App\Support;

class MaterialSanskarCopy
{
    /**
     * @param  array<string, mixed>  $plan
     * @return array<string, mixed>
     */
    public static function forLanguage(array $plan, string $lang): array
    {
        $biz = (string) ($plan['business_name'] ?? '');
        $keep = MaterialIndicScript::keepNames($biz);
        $offer = MaterialIndicScript::phrase($lang, MaterialSanskarCalendar::shortLine((string) ($plan['product'] ?? $plan['category'] ?? 'this offer')), $keep);
        $script = fn (string $text) => MaterialIndicScript::phrase($lang, $text, $keep);

        return MaterialIndicScript::apply($lang, [
            'business_type' => $script(self::t($lang, (string) ($plan['business_type'] ?? ''))),
            'model' => (string) ($plan['model'] ?? ''),
            'customers' => array_map(fn ($item) => $script(self::t($lang, (string) $item)), is_array($plan['target_customers'] ?? null) ? $plan['target_customers'] : []),
            'annual_goal' => $script(self::t($lang, (string) ($plan['annual_goal'] ?? ''))),
            'intro_points' => MaterialIndicScript::lines($lang, is_array($plan['intro_points'] ?? null) ? $plan['intro_points'] : [], $keep),
            'product_points' => MaterialIndicScript::lines($lang, is_array($plan['product_points'] ?? null) ? $plan['product_points'] : [], $keep),
            'closing' => self::fill(self::phrases($lang)['closing'] ?? (string) ($plan['closing'] ?? ''), $biz, $offer),
            'calendar' => array_map(function ($row) use ($lang, $script) {
                $row = is_array($row) ? $row : [];

                return [
                    'activity' => $script(self::t($lang, (string) ($row['activity'] ?? ''))),
                ];
            }, is_array($plan['calendar'] ?? null) ? $plan['calendar'] : []),
            'activities' => array_map(function ($activity) use ($lang, $script) {
                $activity = is_array($activity) ? $activity : [];
                $blocks = [];
                foreach (is_array($activity['blocks'] ?? null) ? $activity['blocks'] : [] as $block) {
                    $block = is_array($block) ? $block : [];
                    $blocks[] = [
                        'label' => $script(self::t($lang, (string) ($block['label'] ?? ''))),
                        'items' => array_map(fn ($item) => $script(self::t($lang, (string) $item)), is_array($block['items'] ?? null) ? $block['items'] : []),
                    ];
                }

                return [
                    'title' => $script(self::t($lang, (string) ($activity['title'] ?? ''))),
                    'objective' => $script(self::t($lang, (string) ($activity['objective'] ?? ''))),
                    'blocks' => $blocks,
                    'memory' => $script(self::t($lang, (string) ($activity['memory'] ?? ''))),
                    'certificate' => ! empty($activity['certificate']) ? self::t($lang, 'Yes') : '',
                ];
            }, is_array($plan['activities'] ?? null) ? $plan['activities'] : []),
            'invitation' => self::invitation($lang, $biz, $offer, is_array($plan['invitation'] ?? null) ? $plan['invitation'] : []),
        ], $keep);
    }

    /**
     * @param  array<string, string>  $fallback
     * @return array<string, string>
     */
    private static function invitation(string $lang, string $biz, string $offer, array $fallback): array
    {
        if ($lang === 'en') {
            return [
                'greeting' => 'Dear Customer,',
                'welcome' => 'A warm welcome from '.$biz.'.',
                'invite' => 'You are invited to our special customer relationship programmes through the year.',
                'place' => '📍 Place:',
                'date' => '📅 Date:',
                'time' => '🕒 Time:',
                'benefit' => 'You will get new '.$offer.' solutions, expert guidance, fun activities and networking.',
                'close' => 'Your presence is valuable for us.',
                'signoff' => '— '.$biz.' Team',
            ];
        }

        $p = self::phrases($lang);

        return [
            'greeting' => $p['invite.greeting'] ?? ($fallback['greeting'] ?? ''),
            'welcome' => self::fill($p['invite.welcome'] ?? '', $biz, $offer),
            'invite' => $p['invite.invite'] ?? '',
            'place' => $p['invite.place'] ?? '📍',
            'date' => $p['invite.date'] ?? '📅',
            'time' => $p['invite.time'] ?? '🕒',
            'benefit' => self::fill($p['invite.benefit'] ?? '', $biz, $offer),
            'close' => $p['invite.close'] ?? '',
            'signoff' => '— '.$biz.' Team',
        ];
    }

    private static function t(string $lang, string $text): string
    {
        $text = trim($text);
        if ($text === '' || $lang === 'en') {
            return $text;
        }
        $map = self::phrases($lang);

        return $map[$text] ?? $text;
    }

    private static function fill(string $template, string $biz, string $offer): string
    {
        return strtr($template, ['{biz}' => $biz, '{offer}' => $offer]);
    }

    /**
     * @return array<string, string>
     */
    private static function phrases(string $lang): array
    {
        return match ($lang) {
            'gu' => [
                'Yes' => 'હા',
                'Electrical Trading' => 'ઈલેક્ટ્રિકલ ટ્રેડિંગ',
                'Electrical Contractors' => 'ઈલેક્ટ્રિકલ કોન્ટ્રાક્ટર્સ',
                'Panel Builders' => 'પેનલ બિલ્ડર્સ',
                'Electricians' => 'ઈલેક્ટ્રિશિયન્સ',
                'Dealers' => 'ડીલર્સ',
                'Industrial Clients' => 'ઇન્ડસ્ટ્રિયલ ક્લાયન્ટ્સ',
                'Builders' => 'બિલ્ડર્સ',
                'OEM Customers' => 'OEM કસ્ટમર્સ',
                'Personal Clients' => 'પર્સનલ ક્લાયન્ટ્સ',
                'Repeat Families' => 'રિપીટ ફેમિલીઝ',
                'Retail Customers' => 'રિટેલ કસ્ટમર્સ',
                'Institutional Buyers' => 'ઇન્સ્ટિટ્યૂશનલ બાયર્સ',
                'Local Partners' => 'લોકલ પાર્ટનર્સ',
                'Repeat Clients' => 'રિપીટ ક્લાયન્ટ્સ',
                'Finance' => 'ફાઈનાન્સ',
                'Customer Connect Meet' => 'કસ્ટમર કનેક્ટ મીટ',
                'Welcome Kit Distribution' => 'વેલકમ કિટ ડિસ્ટ્રિબ્યુશન',
                'Product Knowledge Workshop' => 'પ્રોડક્ટ નોલેજ વર્કશોપ',
                'One-Minute Games' => 'વન-મિનિટ ગેમ્સ',
                'One-Minute Games Day' => 'વન-મિનિટ ગેમ્સ ડે',
                'Open House' => 'ઓપન હાઉસ',
                'Family Evening Picnic' => 'ફેમિલી ઈવનિંગ પિકનિક',
                'Partner Appreciation Day' => 'પાર્ટનર એપ્રિસિયેશન ડે',
                'Quality & Trust Workshop' => 'ક્વોલિટી અને ટ્રસ્ટ વર્કશોપ',
                'Sports & Outdoor Day' => 'સ્પોર્ટ્સ અને આઉટડોર ડે',
                'Customer Service Day' => 'કસ્ટમર સર્વિસ ડે',
                'Cultural Night' => 'કલ્ચરલ નાઈટ',
                'Customer Awards' => 'કસ્ટમર એવોર્ડ્સ',
                'Annual Customer Celebration' => 'એન્યુઅલ કસ્ટમર સેલિબ્રેશન',
                'Thank You Evening' => 'થેન્ક યુ ઈવનિંગ',
                'Memory Wall & Photo Day' => 'મેમરી વોલ અને ફોટો ડે',
                'Signature Customer Summit' => 'સિગ્નેચર કસ્ટમર સમિટ',
                'Design-Led Collection Workshop' => 'ડિઝાઈન-લેડ કલેક્શન વર્કશોપ',
                'Client Appreciation Day' => 'ક્લાયન્ટ એપ્રિસિયેશન ડે',
                'Channel Partner Appreciation Day' => 'ચેનલ પાર્ટનર એપ્રિસિયેશન ડે',
                'Parent & Student Appreciation Day' => 'પેરન્ટ અને સ્ટુડન્ટ એપ્રિસિયેશન ડે',
                'Dealer & Family Appreciation Day' => 'ડીલર અને ફેમિલી એપ્રિસિયેશન ડે',
                'Property Guidance Workshop' => 'પ્રોપર્ટી ગાઈડન્સ વર્કશોપ',
                'Learning Outcomes Workshop' => 'લર્નિંગ આઉટકમ્સ વર્કશોપ',
                'Digital Systems Workshop' => 'ડિજિટલ સિસ્ટમ્સ વર્કશોપ',
                'Taste & Occasion Workshop' => 'ટેસ્ટ અને ઓકેઝન વર્કશોપ',
                'ABB Switchgear Workshop' => 'ABB સ્વિચગિયર વર્કશોપ',
                'Build introduction with new and existing customers.' => 'નવા અને જૂના ગ્રાહકો સાથે પરિચય બનાવો.',
                'Give every new customer a strong first impression.' => 'દરેક નવા ગ્રાહકને મજબૂત પહેલી છાપ આપો.',
                'Build trust with practical product knowledge.' => 'પ્રેક્ટિકલ પ્રોડક્ટ નોલેજથી વિશ્વાસ બનાવો.',
                'Create a light, memorable experience with customers.' => 'ગ્રાહકો સાથે હળવો અને યાદગાર અનુભવ બનાવો.',
                'Increase trust by showing the warehouse and process.' => 'વેરહાઉસ અને પ્રક્રિયા બતાવીને વિશ્વાસ વધારો.',
                'Strengthen the relationship with the customer family.' => 'ગ્રાહકના પરિવાર સાથે સંબંધ મજબૂત કરો.',
                'Increase trust by showing how the work is done.' => 'કામ કેવી રીતે થાય છે તે બતાવીને વિશ્વાસ વધારો.',
                'Honour loyal customers and partners.' => 'લોયલ કસ્ટમર અને પાર્ટનર્સનું સન્માન કરો.',
                'Honour loyal contractors and dealers.' => 'લોયલ કોન્ટ્રાક્ટર્સ અને ડીલર્સનું સન્માન કરો.',
                'Build understanding of quality and trust.' => 'ક્વોલિટી અને ટ્રસ્ટની સમજ બનાવો.',
                'Build understanding of safety and quality.' => 'સેફ્ટી અને ક્વોલિટીની સમજ બનાવો.',
                'Build team spirit and informal bonding.' => 'ટીમ સ્પિરિટ અને ઇન્ફોર્મલ બોન્ડિંગ બનાવો.',
                'Give help, guidance and service in one place.' => 'એક જ જગ્યાએ મદદ, ગાઈડન્સ અને સર્વિસ આપો.',
                'Give warranty, technical support and product guidance in one place.' => 'એક જ જગ્યાએ વોરંટી, ટેકનિકલ સપોર્ટ અને પ્રોડક્ટ ગાઈડન્સ આપો.',
                'Build a cultural relationship with customers.' => 'કસ્ટમર સાથે કલ્ચરલ રિલેશનશિપ બનાવો.',
                'Publicly recognise the best partners.' => 'બેસ્ટ પાર્ટનર્સનું જાહેર સન્માન કરો.',
                'Host the year grand customer event and new offer launch.' => 'એન્યુઅલ ગ્રાન્ડ કસ્ટમર ઈવેન્ટ અને ન્યૂ ઓફર લોન્ચ કરો.',
                'Personally thank close customers.' => 'નજીકના કસ્ટમરનું વ્યક્તિગત થેન્ક યુ કરો.',
                'Join the year memories into a strong memory wall.' => 'વર્ષની યાદોને મજબૂત મેમરી વોલમાં જોડો.',
                'Make this the largest annual relationship event.' => 'આ સૌથી મોટો એન્યુઅલ રિલેશનશિપ ઈવેન્ટ બનાવો.',
                'Make this the largest annual industry event.' => 'આ સૌથી મોટો એન્યુઅલ ઈન્ડસ્ટ્રી ઈવેન્ટ બનાવો.',
                'Customer Awards Night' => 'કસ્ટમર એવોર્ડ્સ નાઈટ',
                'Safety & Quality Workshop' => 'સેફ્ટી અને ક્વોલિટી વર્કશોપ',
                'Contractor Appreciation Day' => 'કોન્ટ્રાક્ટર એપ્રિસિયેશન ડે',
                'Programme Flow' => 'પ્રોગ્રામ ફ્લો',
                'Kit includes' => 'કિટમાં',
                'Topics' => 'ટોપિક્સ',
                'Audience' => 'ઓડિયન્સ',
                'Fun activities' => 'મજાની એક્ટિવિટી',
                'Show customers' => 'ગ્રાહકોને બતાવો',
                'Include' => 'સામેલ',
                'Activities' => 'એક્ટિવિટી',
                'Registration' => 'રજિસ્ટ્રેશન',
                'Tea & Networking' => 'ચા અને નેટવર્કિંગ',
                'Company Introduction' => 'કંપની ઇન્ટ્રોડક્શન',
                'Group Photo' => 'ગ્રુપ ફોટો',
                'Branded Diary' => 'બ્રાન્ડેડ ડાયરી',
                'Pen' => 'પેન',
                'Product Catalogue' => 'પ્રોડક્ટ કેટલોગ',
                'Thank You Card' => 'થેન્ક યુ કાર્ડ',
                'Warehouse' => 'વેરહાઉસ',
                'Stock System' => 'સ્ટોક સિસ્ટમ',
                'Dispatch Process' => 'ડિસ્પેચ પ્રોસેસ',
                'Quality Process' => 'ક્વોલિટી પ્રોસેસ',
                'Spouse' => 'પતિ/પત્ની',
                'Children' => 'બાળકો',
                'Musical Chairs' => 'મ્યુઝિકલ ચેર્સ',
                'Family Games' => 'ફેમિલી ગેમ્સ',
                'Dinner' => 'ડિનર',
                'Personalized Welcome Photo' => 'પર્સનલાઈઝ્ડ વેલકમ ફોટો',
                'First Impression Kit' => 'ફર્સ્ટ ઇમ્પ્રેશન કિટ',
                'Branded Gifts' => 'બ્રાન્ડેડ ગિફ્ટ્સ',
                'Process Walkthrough' => 'પ્રોસેસ વોકથ્રૂ',
                'Family Photo Frame' => 'ફેમિલી ફોટો ફ્રેમ',
                'Create 16 meaningful experiences with every customer through the year and build a lifetime relationship.' => 'વર્ષ દરમિયાન દરેક ગ્રાહક સાથે 16 અર્થપૂર્ણ અનુભવ બનાવો અને આજીવન સંબંધ ઘડો.',
                'invite.greeting' => 'પ્રિય ગ્રાહકશ્રી,',
                'invite.welcome' => '{biz} તરફથી આપનું હાર્દિક સ્વાગત છે.',
                'invite.invite' => 'આપ અમારી સાથે વર્ષ દરમિયાન યોજાનાર વિશેષ કસ્ટમર રિલેશનશિપ કાર્યક્રમમાં આમંત્રિત છો.',
                'invite.place' => '📍 સ્થળ:',
                'invite.date' => '📅 તારીખ:',
                'invite.time' => '🕒 સમય:',
                'invite.benefit' => 'આ કાર્યક્રમમાં નવા {offer} સોલ્યુશન, એક્સપર્ટ ગાઈડન્સ, મજાની એક્ટિવિટી અને નેટવર્કિંગનો લાભ મળશે.',
                'invite.close' => 'આપની હાજરી અમારે માટે ખૂબ જ મૂલ્યવાન છે.',
                'closing' => '{biz} માટે આ માત્ર ઈવેન્ટ નથી. આ લાંબા ગાળાનો વિશ્વાસ અને રિપીટ બિઝનેસ બનાવવાની કસ્ટમર રિલેશનશિપ સ્ટ્રેટેજી છે.',
            ],
            'hi' => [
                'Yes' => 'हाँ',
                'Electrical Trading' => 'इलेक्ट्रिकल ट्रेडिंग',
                'Electrical Contractors' => 'इलेक्ट्रिकल कॉन्ट्रैक्टर्स',
                'Panel Builders' => 'पैनल बिल्डर्स',
                'Electricians' => 'इलेक्ट्रिशियन',
                'Dealers' => 'डीलर्स',
                'Industrial Clients' => 'इंडस्ट्रियल क्लाइंट्स',
                'Builders' => 'बिल्डर्स',
                'OEM Customers' => 'OEM कस्टमर्स',
                'Personal Clients' => 'पर्सनल क्लाइंट्स',
                'Repeat Families' => 'रिपीट फैमिलीज़',
                'Retail Customers' => 'रिटेल कस्टमर्स',
                'Institutional Buyers' => 'इंस्टिट्यूशनल बायर्स',
                'Local Partners' => 'लोकल पार्टनर्स',
                'Repeat Clients' => 'रिपीट क्लाइंट्स',
                'Finance' => 'फाइनेंस',
                'Customer Connect Meet' => 'कस्टमर कनेक्ट मीट',
                'Welcome Kit Distribution' => 'वेलकम किट डिस्ट्रीब्यूशन',
                'Product Knowledge Workshop' => 'प्रॉडक्ट नॉलेज वर्कशॉप',
                'One-Minute Games' => 'वन-मिनट गेम्स',
                'One-Minute Games Day' => 'वन-मिनट गेम्स डे',
                'Open House' => 'ओपन हाउस',
                'Family Evening Picnic' => 'फैमिली इवनिंग पिकनिक',
                'Partner Appreciation Day' => 'पार्टनर अप्रिशिएशन डे',
                'Quality & Trust Workshop' => 'क्वालिटी और ट्रस्ट वर्कशॉप',
                'Sports & Outdoor Day' => 'स्पोर्ट्स और आउटडोर डे',
                'Customer Service Day' => 'कस्टमर सर्विस डे',
                'Cultural Night' => 'कल्चरल नाइट',
                'Customer Awards' => 'कस्टमर अवॉर्ड्स',
                'Annual Customer Celebration' => 'एनुअल कस्टमर सेलिब्रेशन',
                'Thank You Evening' => 'थैंक यू इवनिंग',
                'Memory Wall & Photo Day' => 'मेमोरी वॉल और फ़ोटो डे',
                'Signature Customer Summit' => 'सिग्नेचर कस्टमर समिट',
                'Design-Led Collection Workshop' => 'डिज़ाइन-लेड कलेक्शन वर्कशॉप',
                'Client Appreciation Day' => 'क्लाइंट अप्रिशिएशन डे',
                'Channel Partner Appreciation Day' => 'चैनल पार्टनर अप्रिशिएशन डे',
                'Parent & Student Appreciation Day' => 'पेरेंट और स्टूडेंट अप्रिशिएशन डे',
                'Dealer & Family Appreciation Day' => 'डीलर और फैमिली अप्रिशिएशन डे',
                'Property Guidance Workshop' => 'प्रॉपर्टी गाइडेंस वर्कशॉप',
                'Learning Outcomes Workshop' => 'लर्निंग आउटकम्स वर्कशॉप',
                'Digital Systems Workshop' => 'डिजिटल सिस्टम्स वर्कशॉप',
                'Taste & Occasion Workshop' => 'टेस्ट और ओकेजन वर्कशॉप',
                'ABB Switchgear Workshop' => 'ABB स्विचगियर वर्कशॉप',
                'Build introduction with new and existing customers.' => 'नए और पुराने ग्राहकों के साथ परिचय बनाएं.',
                'Give every new customer a strong first impression.' => 'हर नए ग्राहक को मज़बूत पहली छाप दें.',
                'Build trust with practical product knowledge.' => 'प्रैक्टिकल प्रॉडक्ट नॉलेज से भरोसा बनाएं.',
                'Create a light, memorable experience with customers.' => 'ग्राहकों के साथ हल्का और यादगार अनुभव बनाएं.',
                'Increase trust by showing the warehouse and process.' => 'वेयरहाउस और प्रक्रिया दिखाकर भरोसा बढ़ाएं.',
                'Strengthen the relationship with the customer family.' => 'ग्राहक के परिवार के साथ रिश्ता मज़बूत करें.',
                'Increase trust by showing how the work is done.' => 'काम कैसे होता है दिखाकर भरोसा बढ़ाएं.',
                'Honour loyal customers and partners.' => 'लॉयल कस्टमर और पार्टनर्स का सम्मान करें.',
                'Honour loyal contractors and dealers.' => 'लॉयल कॉन्ट्रैक्टर्स और डीलर्स का सम्मान करें.',
                'Build understanding of quality and trust.' => 'क्वालिटी और ट्रस्ट की समझ बनाएं.',
                'Build understanding of safety and quality.' => 'सेफ्टी और क्वालिटी की समझ बनाएं.',
                'Build team spirit and informal bonding.' => 'टीम स्पिरिट और इनफॉर्मल बॉन्डिंग बनाएं.',
                'Give help, guidance and service in one place.' => 'एक जगह मदद, गाइडेंस और सर्विस दें.',
                'Give warranty, technical support and product guidance in one place.' => 'एक जगह वारंटी, टेक्निकल सपोर्ट और प्रॉडक्ट गाइडेंस दें.',
                'Build a cultural relationship with customers.' => 'कस्टमर के साथ कल्चरल रिलेशनशिप बनाएं.',
                'Publicly recognise the best partners.' => 'बेस्ट पार्टनर्स का सार्वजनिक सम्मान करें.',
                'Host the year grand customer event and new offer launch.' => 'एनुअल ग्रैंड कस्टमर इवेंट और न्यू ऑफर लॉन्च करें.',
                'Personally thank close customers.' => 'नज़दीकी कस्टमर का व्यक्तिगत थैंक यू करें.',
                'Join the year memories into a strong memory wall.' => 'साल की यादों को मज़बूत मेमोरी वॉल में जोड़ें.',
                'Make this the largest annual relationship event.' => 'यह सबसे बड़ा एनुअल रिलेशनशिप इवेंट बनाएं.',
                'Make this the largest annual industry event.' => 'यह सबसे बड़ा एनुअल इंडस्ट्री इवेंट बनाएं.',
                'Customer Awards Night' => 'कस्टमर अवॉर्ड्स नाइट',
                'Safety & Quality Workshop' => 'सेफ्टी और क्वालिटी वर्कशॉप',
                'Contractor Appreciation Day' => 'कॉन्ट्रैक्टर अप्रिशिएशन डे',
                'Programme Flow' => 'प्रोग्राम फ्लो',
                'Kit includes' => 'किट में',
                'Topics' => 'टॉपिक्स',
                'Audience' => 'ऑडियंस',
                'Fun activities' => 'मज़ेदार एक्टिविटी',
                'Show customers' => 'ग्राहकों को दिखाएं',
                'Include' => 'शामिल',
                'Activities' => 'एक्टिविटी',
                'Registration' => 'रजिस्ट्रेशन',
                'Tea & Networking' => 'चाय और नेटवर्किंग',
                'Company Introduction' => 'कंपनी इंट्रोडक्शन',
                'Group Photo' => 'ग्रुप फ़ोटो',
                'Branded Diary' => 'ब्रांडेड डायरी',
                'Pen' => 'पेन',
                'Product Catalogue' => 'प्रॉडक्ट कैटलॉग',
                'Thank You Card' => 'थैंक यू कार्ड',
                'Warehouse' => 'वेयरहाउस',
                'Stock System' => 'स्टॉक सिस्टम',
                'Dispatch Process' => 'डिस्पैच प्रोसेस',
                'Quality Process' => 'क्वालिटी प्रोसेस',
                'Spouse' => 'पति/पत्नी',
                'Children' => 'बच्चे',
                'Musical Chairs' => 'म्यूज़िकल चेयर्स',
                'Family Games' => 'फैमिली गेम्स',
                'Dinner' => 'डिनर',
                'Personalized Welcome Photo' => 'पर्सनलाइज़्ड वेलकम फ़ोटो',
                'First Impression Kit' => 'फर्स्ट इंप्रेशन किट',
                'Branded Gifts' => 'ब्रांडेड गिफ्ट्स',
                'Process Walkthrough' => 'प्रोसेस वॉकथ्रू',
                'Family Photo Frame' => 'फैमिली फ़ोटो फ्रेम',
                'Create 16 meaningful experiences with every customer through the year and build a lifetime relationship.' => 'साल भर हर ग्राहक के साथ 16 अर्थपूर्ण अनुभव बनाएं और आजीवन रिश्ता बनाएं.',
                'invite.greeting' => 'प्रिय ग्राहकजी,',
                'invite.welcome' => '{biz} की तरफ़ से आपका हार्दिक स्वागत है.',
                'invite.invite' => 'आप हमारे साल भर चलने वाले विशेष कस्टमर रिलेशनशिप कार्यक्रम में आमंत्रित हैं.',
                'invite.place' => '📍 स्थान:',
                'invite.date' => '📅 तारीख:',
                'invite.time' => '🕒 समय:',
                'invite.benefit' => 'इस कार्यक्रम में नए {offer} सॉल्यूशन, एक्सपर्ट गाइडेंस, मज़ेदार एक्टिविटी और नेटवर्किंग मिलेगी.',
                'invite.close' => 'आपकी उपस्थिति हमारे लिए बहुत मूल्यवान है.',
                'closing' => '{biz} के लिए यह केवल इवेंट नहीं है. यह लंबे समय का भरोसा और रिपीट बिज़नेस बनाने की कस्टमर रिलेशनशिप रणनीति है.',
            ],
            'mr' => [
                'Yes' => 'हो',
                'Electrical Trading' => 'इलेक्ट्रिकल ट्रेडिंग',
                'Electrical Contractors' => 'इलेक्ट्रिकल कॉन्ट्रॅक्टर्स',
                'Panel Builders' => 'पॅनल बिल्डर्स',
                'Electricians' => 'इलेक्ट्रिशियन',
                'Dealers' => 'डीलर्स',
                'Industrial Clients' => 'इंडस्ट्रियल क्लायंट्स',
                'Builders' => 'बिल्डर्स',
                'OEM Customers' => 'OEM कस्टमर',
                'Personal Clients' => 'पर्सनल क्लायंट्स',
                'Repeat Families' => 'रिपीट फॅमिलीज',
                'Retail Customers' => 'रिटेल कस्टमर',
                'Institutional Buyers' => 'इन्स्टिट्यूशनल बायर्स',
                'Local Partners' => 'लोकल पार्टनर्स',
                'Repeat Clients' => 'रिपीट क्लायंट्स',
                'Finance' => 'फायनान्स',
                'Customer Connect Meet' => 'कस्टमर कनेक्ट मीट',
                'Welcome Kit Distribution' => 'वेलकम किट डिस्ट्रिब्युशन',
                'Product Knowledge Workshop' => 'प्रॉडक्ट नॉलेज वर्कशॉप',
                'One-Minute Games' => 'वन-मिनिट गेम्स',
                'One-Minute Games Day' => 'वन-मिनिट गेम्स डे',
                'Open House' => 'ओपन हाउस',
                'Family Evening Picnic' => 'फॅमिली इव्हिनिंग पिकनिक',
                'Partner Appreciation Day' => 'पार्टनर अॅप्रिसिएशन डे',
                'Quality & Trust Workshop' => 'क्वालिटी आणि ट्रस्ट वर्कशॉप',
                'Sports & Outdoor Day' => 'स्पोर्ट्स आणि आउटडोअर डे',
                'Customer Service Day' => 'कस्टमर सर्व्हिस डे',
                'Cultural Night' => 'कल्चरल नाईट',
                'Customer Awards' => 'कस्टमर अवॉर्ड्स',
                'Annual Customer Celebration' => 'अॅन्युअल कस्टमर सेलिब्रेशन',
                'Thank You Evening' => 'थँक यू इव्हिनिंग',
                'Memory Wall & Photo Day' => 'मेमरी वॉल आणि फोटो डे',
                'Signature Customer Summit' => 'सिग्नेचर कस्टमर समिट',
                'Design-Led Collection Workshop' => 'डिझाइन-लेड कलेक्शन वर्कशॉप',
                'Client Appreciation Day' => 'क्लायंट अॅप्रिसिएशन डे',
                'Channel Partner Appreciation Day' => 'चॅनल पार्टनर अॅप्रिसिएशन डे',
                'Parent & Student Appreciation Day' => 'पालक आणि विद्यार्थी अॅप्रिसिएशन डे',
                'Dealer & Family Appreciation Day' => 'डीलर आणि फॅमिली अॅप्रिसिएशन डे',
                'Property Guidance Workshop' => 'प्रॉपर्टी गाइडन्स वर्कशॉप',
                'Learning Outcomes Workshop' => 'लर्निंग आऊटकम्स वर्कशॉप',
                'Digital Systems Workshop' => 'डिजिटल सिस्टम्स वर्कशॉप',
                'Taste & Occasion Workshop' => 'टेस्ट आणि ओकेजन वर्कशॉप',
                'ABB Switchgear Workshop' => 'ABB स्विचगियर वर्कशॉप',
                'Build introduction with new and existing customers.' => 'नवे आणि जुने ग्राहक यांच्याशी परिचय तयार करा.',
                'Give every new customer a strong first impression.' => 'प्रत्येक नव्या ग्राहकाला मजबूत पहिली छाप द्या.',
                'Build trust with practical product knowledge.' => 'प्रॅक्टिकल प्रॉडक्ट नॉलेजने विश्वास तयार करा.',
                'Create a light, memorable experience with customers.' => 'ग्राहकांसोबत हलका आणि आठवणीत राहणारा अनुभव तयार करा.',
                'Increase trust by showing the warehouse and process.' => 'वेअरहाऊस आणि प्रक्रिया दाखवून विश्वास वाढवा.',
                'Strengthen the relationship with the customer family.' => 'ग्राहकाच्या कुटुंबासोबत नाते मजबूत करा.',
                'Increase trust by showing how the work is done.' => 'काम कसे होते ते दाखवून विश्वास वाढवा.',
                'Honour loyal customers and partners.' => 'लॉयल कस्टमर आणि पार्टनर्सचा सन्मान करा.',
                'Honour loyal contractors and dealers.' => 'लॉयल कॉन्ट्रॅक्टर्स आणि डीलर्सचा सन्मान करा.',
                'Build understanding of quality and trust.' => 'क्वालिटी आणि ट्रस्टची समज तयार करा.',
                'Build understanding of safety and quality.' => 'सेफ्टी आणि क्वालिटीची समज तयार करा.',
                'Build team spirit and informal bonding.' => 'टीम स्पिरिट आणि इन्फॉर्मल बॉन्डिंग तयार करा.',
                'Give help, guidance and service in one place.' => 'एकत्र मदत, गाइडन्स आणि सर्व्हिस द्या.',
                'Give warranty, technical support and product guidance in one place.' => 'एकत्र वॉरंटी, टेक्निकल सपोर्ट आणि प्रॉडक्ट गाइडन्स द्या.',
                'Build a cultural relationship with customers.' => 'कस्टमरसोबत कल्चरल रिलेशनशिप तयार करा.',
                'Publicly recognise the best partners.' => 'बेस्ट पार्टनर्सचा सार्वजनिक सन्मान करा.',
                'Host the year grand customer event and new offer launch.' => 'अॅन्युअल ग्रँड कस्टमर इव्हेंट आणि न्यू ऑफर लॉन्च करा.',
                'Personally thank close customers.' => 'जवळच्या कस्टमरचे व्यक्तिगत थँक यू करा.',
                'Join the year memories into a strong memory wall.' => 'वर्षभराच्या आठवणी एका मजबूत मेमरी वॉलमध्ये जोडा.',
                'Make this the largest annual relationship event.' => 'हा सर्वात मोठा अॅन्युअल रिलेशनशिप इव्हेंट बनवा.',
                'Make this the largest annual industry event.' => 'हा सर्वात मोठा अॅन्युअल इंडस्ट्री इव्हेंट बनवा.',
                'Customer Awards Night' => 'कस्टमर अवॉर्ड्स नाईट',
                'Safety & Quality Workshop' => 'सेफ्टी आणि क्वालिटी वर्कशॉप',
                'Contractor Appreciation Day' => 'कॉन्ट्रॅक्टर अॅप्रिसिएशन डे',
                'Programme Flow' => 'प्रोग्राम फ्लो',
                'Kit includes' => 'किटमध्ये',
                'Topics' => 'टॉपिक्स',
                'Audience' => 'ऑडियन्स',
                'Fun activities' => 'मजेदार अॅक्टिव्हिटी',
                'Show customers' => 'ग्राहकांना दाखवा',
                'Include' => 'समाविष्ट',
                'Activities' => 'अॅक्टिव्हिटी',
                'Registration' => 'रजिस्ट्रेशन',
                'Tea & Networking' => 'चहा आणि नेटवर्किंग',
                'Company Introduction' => 'कंपनी इंट्रोडक्शन',
                'Group Photo' => 'ग्रुप फोटो',
                'Branded Diary' => 'ब्रँडेड डायरी',
                'Pen' => 'पेन',
                'Product Catalogue' => 'प्रॉडक्ट कॅटलॉग',
                'Thank You Card' => 'थँक यू कार्ड',
                'Warehouse' => 'वेअरहाऊस',
                'Stock System' => 'स्टॉक सिस्टम',
                'Dispatch Process' => 'डिस्पॅच प्रोसेस',
                'Quality Process' => 'क्वालिटी प्रोसेस',
                'Spouse' => 'पती/पत्नी',
                'Children' => 'मुले',
                'Musical Chairs' => 'म्युझिकल चेअर्स',
                'Family Games' => 'फॅमिली गेम्स',
                'Dinner' => 'डिनर',
                'Personalized Welcome Photo' => 'पर्सनलाइज्ड वेलकम फोटो',
                'First Impression Kit' => 'फर्स्ट इंप्रेशन किट',
                'Branded Gifts' => 'ब्रँडेड गिफ्ट्स',
                'Process Walkthrough' => 'प्रोसेस वॉकथ्रू',
                'Family Photo Frame' => 'फॅमिली फोटो फ्रेम',
                'Create 16 meaningful experiences with every customer through the year and build a lifetime relationship.' => 'वर्षभर प्रत्येक ग्राहकासोबत 16 अर्थपूर्ण अनुभव तयार करा आणि आयुष्यभराचे नाते घडवा.',
                'invite.greeting' => 'प्रिय ग्राहकश्री,',
                'invite.welcome' => '{biz} कडून आपले हार्दिक स्वागत आहे.',
                'invite.invite' => 'आपण आमच्या वर्षभरातील विशेष कस्टमर रिलेशनशिप कार्यक्रमात आमंत्रित आहात.',
                'invite.place' => '📍 स्थळ:',
                'invite.date' => '📅 तारीख:',
                'invite.time' => '🕒 वेळ:',
                'invite.benefit' => 'या कार्यक्रमात नवीन {offer} सोल्यूशन्स, एक्सपर्ट गाइडन्स, मजेदार अॅक्टिव्हिटी आणि नेटवर्किंग मिळेल.',
                'invite.close' => 'आपली उपस्थिती आमच्यासाठी खूप मौल्यवान आहे.',
                'closing' => '{biz} साठी हे फक्त इव्हेंट नाही. ही दीर्घकाळचा विश्वास आणि रिपीट बिझनेस तयार करणारी कस्टमर रिलेशनशिप स्ट्रॅटेजी आहे.',
            ],
            default => [],
        };
    }
}
